CREATE SCHEMA LEARNING_SYSTEM;
USE LEARNING_SYSTEM;

CREATE TABLE PERSON (
	SSN CHAR(9) PRIMARY KEY CHECK(SSN REGEXP '[0-9]{9}'),
    FNAME VARCHAR(15),
    LNAME VARCHAR(15),
    GENDER CHAR CHECK(GENDER IN ('M', 'F')),
    BIRTHDAY DATE,
    EMAIL VARCHAR(15) CHECK(EMAIL LIKE '%@%')
);

CREATE TABLE FACULTY (
	FACULTY_CODE CHAR(9) PRIMARY KEY,
    FACULTY_NAME VARCHAR(15)
);

CREATE TABLE AUTHOR (
	AUTHOR_ID CHAR(9) PRIMARY KEY
);

CREATE TABLE PUBLISHER (
	PUBLISHER_NAME VARCHAR(15) PRIMARY KEY
);

CREATE TABLE STUDENT (
	STUDENT_ID CHAR(7) PRIMARY KEY CHECK (STUDENT_ID REGEXP '[0-9]{7}'),
    SSN CHAR(9) UNIQUE NOT NULL CHECK (SSN REGEXP '[0-9]{9}'),
    GPA DECIMAL(3, 1) CHECK(GPA >= 0 AND GPA <= 10),
    FCODE CHAR(9) NOT NULL,
    FOREIGN KEY (FCODE) REFERENCES FACULTY(FACULTY_CODE),
    FOREIGN KEY (SSN) REFERENCES PERSON(SSN)
);

CREATE TABLE STAFF (
	STAFF_ID CHAR(7) PRIMARY KEY CHECK (STAFF_ID REGEXP '[0-9]{7}'),
    SSN CHAR(9) UNIQUE NOT NULL CHECK (SSN REGEXP '[0-9]{9}'),
    FCODE CHAR(9) NOT NULL,
    FOREIGN KEY (FCODE) REFERENCES FACULTY(FACULTY_CODE),
    FOREIGN KEY (SSN) REFERENCES PERSON(SSN)
);

CREATE TABLE MANAGEMENT_INSTRUCTOR(
	STAFF_ID CHAR(7) PRIMARY KEY,
    ACADEMIC_RANK VARCHAR(3) CHECK (ACADEMIC_RANK IN ('GS', 'PGS')),
    EXPERIENCE INT CHECK(EXPERIENCE >= 0),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE INSTRUCTOR (
	STAFF_ID CHAR(7) PRIMARY KEY,
    DEGREE VARCHAR(9) CHECK (DEGREE IN ('Bachelor', 'Master', 'Doctor')),
    MGR_ID CHAR(7) NOT NULL,
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    FOREIGN KEY (MGR_ID) REFERENCES MANAGEMENT_INSTRUCTOR(STAFF_ID)
);

CREATE TABLE AAO_STAFF (
	STAFF_ID CHAR(7) PRIMARY KEY,
    SKILL VARCHAR(15),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE MAJOR_INSTRUCTOR(
	STAFF_ID CHAR(7) PRIMARY KEY,
    FOREIGN KEY (STAFF_ID) REFERENCES INSTRUCTOR(STAFF_ID)
);

CREATE TABLE DOCUMENT(
	ISBN CHAR(17) PRIMARY KEY CHECK (ISBN REGEXP '[0-9]{3}-[0-9]-[0-9]{6}-[0-9]{2}-[0-9]'),
    DOCUMENT_NAME VARCHAR(15),
    PUBLISHER_NAME VARCHAR(15) NOT NULL,
    FOREIGN KEY (PUBLISHER_NAME) REFERENCES PUBLISHER(PUBLISHER_NAME)
);

CREATE TABLE COURSE(
	COURSE_ID CHAR(5) PRIMARY KEY,
    COURSE_NAME VARCHAR(15),
    CREDIT INT CHECK (CREDIT >= 1 AND CREDIT <= 3),
    FCODE CHAR(9) NOT NULL,
    FOREIGN KEY (FCODE) REFERENCES FACULTY(FACULTY_CODE)
);

CREATE TABLE CLASS (
	COURSE_ID CHAR(5),
    CLASS_ID CHAR(5),
    SEMESTER INT NOT NULL CHECK (SEMESTER >= 1 AND SEMESTER <= 3), -- HỌC KỲ
    CYEAR INT NOT NULL CHECK (CYEAR > 0),
    PERIOD INT CHECK (PERIOD > 0), -- SỐ TIẾT
    AMOUNT INT,
    PRIMARY KEY (COURSE_ID, CLASS_ID),
    CONSTRAINT SECONDARY_KEY UNIQUE (SEMESTER, CYEAR),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE CLASS_GROUP (
	COURSE_ID CHAR(5),
    CLASS_ID CHAR(5),
    ORDER_NO INT CHECK (ORDER_NO > 0),
    PRIMARY KEY (COURSE_ID, CLASS_ID, ORDER_NO),
    FOREIGN KEY (COURSE_ID, CLASS_ID) REFERENCES CLASS(COURSE_ID, CLASS_ID)
);

CREATE TABLE WEEK_OF_STUDY (
	COURSE_ID CHAR(5),
    CLASS_ID CHAR(5),
    ORDER_NO INT,
    WEEK_ORDER_NO INT CHECK (WEEK_ORDER_NUMBER > 0),
    PRIMARY KEY (COURSE_ID, CLASS_ID, ORDER_NO, WEEK_ORDER_NO),
    FOREIGN KEY (COURSE_ID, CLASS_ID, ORDER_NO) REFERENCES CLASS_GROUP(COURSE_ID, CLASS_ID, ORDER_NO)
);

CREATE TABLE REGISTER (
	STUDENT_ID CHAR(7),
    COURSE_ID CHAR(5),
    REGISTER_TIME DATETIME,
    PRIMARY KEY (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

insert 

GRANT ALL privileges ON LEARNING_SYSTEM.* to 'root';

-- CREATE TABLE PARRALLEL_COURSE (
-- 	
-- );